# Copyright (c) 2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

description: Macro Behavior

compatible: "zmk,behavior-macro"

include: zero_param.yaml

properties:
  bindings:
    type: phandle-array
    required: true
  wait-ms:
    type: int
    default: 100
    description: The default time to wait (in milliseconds) before triggering the next behavior in the macro bindings list.
  tap-ms:
    type: int
    default: 100
    description: The default time to wait (in milliseconds) between the press and release events on a tapped macro behavior binding