# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: dactyl_manuform_4x6_left
  - board: nice_nano_v2
    shield: dactyl_manuform_4x6_right
  - board: nordic_nrf52840_dongle_slicemk 
    shield: dactyl_manuform_4x6_dongle
  - board: nice_nano_v2
    shield: settings_reset
  - board: nordic_nrf52840_dongle_slicemk 
    shield: reset_nrf52840_dongle
  - board: nice_nano_v2
    shield: tbk-mini_left
  - board: nice_nano_v2
    shield: tbk-mini_right
  - board: nordic_nrf52840_dongle_slicemk 
    shield: tbk-mini_dongle
  - board: nice_nano_v2
    shield: cmini_left
  - board: nice_nano_v2
    shield: cmini_right
  - board: nordic_nrf52840_dongle_slicemk 
    shield: cmini_dongle