manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: slicemk
      url-base: https://github.com/wdtamagi/slicemk
  projects:
    - name: zmk
      remote: slicemk
      revision: v20220204-dactyl
      import: app/west.yml
  self:
    path: config
