manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tongfeng
      url-base: https://github.com/fengzixiaopi
  projects:
    - name: zmk
      remote: tongfeng
      revision: ptdevice
      import: app/west.yml
  self:
    path: config
