manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: okke-formsma
      url-base: https://github.com/okke-formsma
  projects:
    - name: zmk-key-repeat
      remote: petejohanson
      revision: behaviors/key-repeat
      import: app/west.yml
    - name: zmk-macros
      remote: okke-formsma
      revision: macros
      import: app/west.yml
  self:
    path: config