manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/drorchen
  projects:
    - name: zmk
      remote: zmk
      revision: trackball-support
      import: app/west.yml
  self:
    path: config