file_format: "1"
id: dactyl_manuform_4x6
name: dactyl_manuform_4x6
type: shield
requires:
  - pro_micro
features:
  - keys
siblings:
  - dactyl_manuform_4x6_left
  - dactyl_manuform_4x6_right
  - dactyl_manuform_4x6_dongle